-- BOOKISTUDIO — Supabase schema for contact + intake submissions.
-- Run this once in your Supabase SQL Editor (Project → SQL Editor → New query → Paste → Run).

-- ── Table ──────────────────────────────────────────────────────────────
create table if not exists public.inquiries (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  type        text not null check (type in ('contact', 'intake')),
  name        text,
  email       text,
  business    text,
  budget      text,
  read        boolean not null default false,
  data        jsonb not null default '{}'::jsonb
);

create index if not exists inquiries_created_at_idx on public.inquiries (created_at desc);
create index if not exists inquiries_type_idx       on public.inquiries (type);
create index if not exists inquiries_read_idx       on public.inquiries (read);

-- ── Row Level Security ────────────────────────────────────────────────
alter table public.inquiries enable row level security;

-- Anyone (anon or signed-in) can submit a form.
drop policy if exists "Anyone can insert inquiries" on public.inquiries;
create policy "Anyone can insert inquiries"
  on public.inquiries
  for insert
  to anon, authenticated
  with check (type in ('contact', 'intake'));

-- Only signed-in admins can read.
drop policy if exists "Authenticated can read inquiries" on public.inquiries;
create policy "Authenticated can read inquiries"
  on public.inquiries
  for select
  to authenticated
  using (true);

-- Only signed-in admins can mark read / unread.
drop policy if exists "Authenticated can update inquiries" on public.inquiries;
create policy "Authenticated can update inquiries"
  on public.inquiries
  for update
  to authenticated
  using (true)
  with check (true);

-- Only signed-in admins can delete.
drop policy if exists "Authenticated can delete inquiries" on public.inquiries;
create policy "Authenticated can delete inquiries"
  on public.inquiries
  for delete
  to authenticated
  using (true);

-- ── Storage bucket for intake-form uploads ─────────────────────────────
-- Create the bucket (idempotent). Public so the admin dashboard can preview
-- and download files without signed URLs. Files are namespaced under random
-- prefixes so there is effectively no enumeration risk.
insert into storage.buckets (id, name, public)
values ('intake-files', 'intake-files', true)
on conflict (id) do update set public = true;

-- Anyone can upload into the intake-files bucket (so customers can attach
-- files via the public intake form).
drop policy if exists "Anyone can upload intake files" on storage.objects;
create policy "Anyone can upload intake files"
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id = 'intake-files');

-- Anyone can read intake files (the bucket is public; this policy makes
-- the public URLs actually serve).
drop policy if exists "Anyone can read intake files" on storage.objects;
create policy "Anyone can read intake files"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'intake-files');

-- Only signed-in admins can delete uploaded files.
drop policy if exists "Authenticated can delete intake files" on storage.objects;
create policy "Authenticated can delete intake files"
  on storage.objects
  for delete
  to authenticated
  using (bucket_id = 'intake-files');
