-- BOOKISTUDIO — Supabase schema for contact + intake submissions.
-- Run this once in your Supabase SQL Editor (Project → SQL Editor → New query → Paste → Run).

-- ── Table ──────────────────────────────────────────────────────────────
create table if not exists public.inquiries (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  type        text not null check (type in ('contact', 'intake')),
  name        text,
  email       text,
  business    text,
  budget      text,
  read        boolean not null default false,
  data        jsonb not null default '{}'::jsonb
);

create index if not exists inquiries_created_at_idx on public.inquiries (created_at desc);
create index if not exists inquiries_type_idx       on public.inquiries (type);
create index if not exists inquiries_read_idx       on public.inquiries (read);

-- ── Row Level Security ────────────────────────────────────────────────
alter table public.inquiries enable row level security;

-- Anyone (anon or signed-in) can submit a form.
drop policy if exists "Anyone can insert inquiries" on public.inquiries;
create policy "Anyone can insert inquiries"
  on public.inquiries
  for insert
  to anon, authenticated
  with check (type in ('contact', 'intake'));

-- Only signed-in admins can read.
drop policy if exists "Authenticated can read inquiries" on public.inquiries;
create policy "Authenticated can read inquiries"
  on public.inquiries
  for select
  to authenticated
  using (true);

-- Only signed-in admins can mark read / unread.
drop policy if exists "Authenticated can update inquiries" on public.inquiries;
create policy "Authenticated can update inquiries"
  on public.inquiries
  for update
  to authenticated
  using (true)
  with check (true);

-- Only signed-in admins can delete.
drop policy if exists "Authenticated can delete inquiries" on public.inquiries;
create policy "Authenticated can delete inquiries"
  on public.inquiries
  for delete
  to authenticated
  using (true);

-- ── Sites table (admin-managed portfolio entries) ─────────────────────
create table if not exists public.sites (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  name         text not null,
  url          text not null,
  industry     text,
  description  text,
  image_data   text,  -- base64 data-URL of the thumbnail image
  active       boolean not null default true
);

create index if not exists sites_created_at_idx on public.sites (created_at desc);
create index if not exists sites_active_idx     on public.sites (active);

-- ── Row Level Security for sites ─────────────────────────────────────
alter table public.sites enable row level security;

-- Anyone (anon + authenticated) can read active sites (for the public portfolio grid).
drop policy if exists "Anyone can read active sites" on public.sites;
create policy "Anyone can read active sites"
  on public.sites
  for select
  to anon, authenticated
  using (active = true);

-- Only authenticated admins can insert, update, or delete sites.
drop policy if exists "Authenticated can insert sites" on public.sites;
create policy "Authenticated can insert sites"
  on public.sites
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated can update sites" on public.sites;
create policy "Authenticated can update sites"
  on public.sites
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated can delete sites" on public.sites;
create policy "Authenticated can delete sites"
  on public.sites
  for delete
  to authenticated
  using (true);
